# Generated by Django 4.1.1 on 2022-09-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Account',
            fields=[
                ('provider', models.CharField(max_length=255)),
                ('provider_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('account_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth2 Account',
                'verbose_name_plural': 'OAuth2 Accounts',
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
